model:
  _target_: osa.models.factory.SynthModel
  backbone:
    _target_: osa.models.factory.HybridBackbone
    input_size: 4
    d_model: 32
    blocks:
      - _target_: osa.models.registry.TransformerBlock
        d_model: 32
        nhead: 4
      - _target_: osa.models.components.advanced_blocks.LayerNormBlock
        d_model: 32
      - _target_: osa.models.registry.LSTMBlock
        d_model: 32
        num_layers: 1
      - _target_: osa.models.components.advanced_blocks.LayerNormBlock
        d_model: 32
      - _target_: osa.models.registry.TransformerBlock
        d_model: 32
        nhead: 2
  head:
    _target_: osa.models.heads.GBMHead
    latent_size: 32
